server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:mysql://localhost:3306/authorization_server?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update